In [18]:
import pandas as pd
import numpy as np
import plotly as px

In [19]:
profile = pd.read_excel("Datasets/Client Profiles.xlsx")
survey = pd.read_excel("Datasets/Client Survey.xlsx")
cogs = pd.read_excel("Datasets/Revenue and COGS.xlsx")

In [20]:
profile['COUNTRY'] = np.where(profile['SG-BASED'].str.lower().isin(['yes', 'y']), 'Singapore', profile['COUNTRY OF OVERSEAS CLIENT'])

In [21]:
profile['STAFF STRENGTH'] = profile['STAFF STRENGTH'].replace({'More than 200': "> 200", 'Less than 200': "50 ~ 200", 'Less than 49': "1 ~ 49"})

In [22]:
cogs

    CLIENT ID  YEAR  REVENUE  HARDWARE  SOFTWARE  MANPOWER
0      G1-001  2021   148180     17321     25562     41201
1      G1-001  2022   197313     23604     32875     50085
2      G1-001  2023   349899     51332     71695     89089
3      G1-001  2024   268821     40969     56452     76545
4      G1-001  2025   138115     14516     20889     28968
..        ...   ...      ...       ...       ...       ...
418    P3-027  2025   172191     17127     35088     52215
419    P3-028  2025   220048     15847     45103     91424
420    P3-029  2025   279839     22351     45673     70801
421    P3-030  2025   146829     14505     30602     43338
422    P3-031  2025   275305     19834     41006     60840

[423 rows x 6 columns]

In [23]:
# Merge the three datasets into a single dataframe on Client ID
client_id_candidates = ["Client ID", "CLIENT ID", "ClientID", "CLIENTID", "client_id", "Client_Id", "Client Id"]


def _resolve_client_id(df, df_name):
    for candidate in client_id_candidates:
        if candidate in df.columns:
            return candidate
    raise KeyError(f"No client ID column found in {df_name}. Checked: {client_id_candidates}")

profile_id = _resolve_client_id(profile, "profile")
survey_id = _resolve_client_id(survey, "survey")
cogs_id = _resolve_client_id(cogs, "cogs")


df = (
    profile.rename(columns={profile_id: "Client ID"})
    .merge(survey.rename(columns={survey_id: "Client ID"}), on="Client ID", how="left", suffixes=('', '_survey'))
    .merge(cogs.rename(columns={cogs_id: "Client ID"}), on="Client ID", how="left", suffixes=('', '_cogs'))
)

df.head()

,Client ID,TYPE,SG-BASED,OVERSEAS,COUNTRY OF OVERSEAS CLIENT,COMMENCEMENT DATE,STAFF STRENGTH,SECTOR,COUNTRY,YEAR,PRESALES AND PARTNERSHIP,TECHNICAL EXPERTISE,PROJECT DELIVERY,POST-SALES SUPPORT,NPS RATING,YEAR_cogs,REVENUE,HARDWARE,SOFTWARE,MANPOWER
0,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore,2021.0,3.0,4.0,4.0,5.0,8.0,2021.0,148180.0,17321.0,25562.0,41201.0
1,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore,2021.0,3.0,4.0,4.0,5.0,8.0,2022.0,197313.0,23604.0,32875.0,50085.0
2,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore,2021.0,3.0,4.0,4.0,5.0,8.0,2023.0,349899.0,51332.0,71695.0,89089.0
3,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore,2021.0,3.0,4.0,4.0,5.0,8.0,2024.0,268821.0,40969.0,56452.0,76545.0
4,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore,2021.0,3.0,4.0,4.0,5.0,8.0,2025.0,138115.0,14516.0,20889.0,28968.0

In [24]:
df

,Client ID,TYPE,SG-BASED,OVERSEAS,COUNTRY OF OVERSEAS CLIENT,COMMENCEMENT DATE,STAFF STRENGTH,SECTOR,COUNTRY,YEAR,PRESALES AND PARTNERSHIP,TECHNICAL EXPERTISE,PROJECT DELIVERY,POST-SALES SUPPORT,NPS RATING,YEAR_cogs,REVENUE,HARDWARE,SOFTWARE,MANPOWER
0,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore,2021.0,3.0,4.0,4.0,5.0,8.0,2021.0,148180.0,17321.0,25562.0,41201.0
1,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore,2021.0,3.0,4.0,4.0,5.0,8.0,2022.0,197313.0,23604.0,32875.0,50085.0
2,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore,2021.0,3.0,4.0,4.0,5.0,8.0,2023.0,349899.0,51332.0,71695.0,89089.0
3,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore,2021.0,3.0,4.0,4.0,5.0,8.0,2024.0,268821.0,40969.0,56452.0,76545.0
4,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore,2021.0,3.0,4.0,4.0,5.0,8.0,2025.0,138115.0,14516.0,20889.0,28968.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1532,P3-027,Private,,Y,Malaysian,2025-01-04 00:00:00,> 200,Info Tech,Malaysian,2025.0,4.0,5.0,5.0,3.0,9.0,2025.0,172191.0,17127.0,35088.0,52215.0
1533,P3-028,Private,NaN,Y,India,2025-01-14 00:00:00,50 ~ 200,Info Tech,India,2025.0,4.0,5.0,5.0,5.0,9.0,2025.0,220048.0,15847.0,45103.0,91424.0
1534,P3-029,Private,,Y,Malaysia,2025-04-04 00:00:00,> 200,Healthcare,Malaysia,2025.0,5.0,2.0,4.0,5.0,9.0,2025.0,279839.0,22351.0,45673.0,70801.0
1535,P3-030,Private,NaN,Y,Indonesia,2025-05-04 00:00:00,50 ~ 200,Healthcare,Indonesia,2025.0,3.0,3.0,3.0,3.0,6.0,2025.0,146829.0,14505.0,30602.0,43338.0
1536,P3-031,Private,NaN,Y,India,2025-07-14 00:00:00,> 200,Manufacturing,India,2025.0,5.0,4.0,3.0,4.0,7.0,2025.0,275305.0,19834.0,41006.0,60840.0

In [25]:
profile

,CLIENT ID,TYPE,SG-BASED,OVERSEAS,COUNTRY OF OVERSEAS CLIENT,COMMENCEMENT DATE,STAFF STRENGTH,SECTOR,COUNTRY
0,G1-001,Govt,Yes,NaN,,2020-01-19 00:00:00,> 200,Finance,Singapore
1,G1-002,Govt,Yes,NaN,,2020-05-19 00:00:00,> 200,Security,Singapore
2,G1-003,Govt,Yes,NaN,,2021-07-18 00:00:00,> 200,Transportation,Singapore
3,G1-005,Govt,Y,NaN,NaN,2022-02-11 00:00:00,> 200,Security,Singapore
4,G1-006,Govt,Y,NaN,NaN,2022-03-18 00:00:00,50 ~ 200,Legal,Singapore
...,...,...,...,...,...,...,...,...,...
143,P3-027,Private,,Y,Malaysian,2025-01-04 00:00:00,> 200,Info Tech,Malaysian
144,P3-028,Private,NaN,Y,India,2025-01-14 00:00:00,50 ~ 200,Info Tech,India
145,P3-029,Private,,Y,Malaysia,2025-04-04 00:00:00,> 200,Healthcare,Malaysia
146,P3-030,Private,NaN,Y,Indonesia,2025-05-04 00:00:00,50 ~ 200,Healthcare,Indonesia
147,P3-031,Private,NaN,Y,India,2025-07-14 00:00:00,> 200,Manufacturing,India

In [26]:
cogs

    CLIENT ID  YEAR  REVENUE  HARDWARE  SOFTWARE  MANPOWER
0      G1-001  2021   148180     17321     25562     41201
1      G1-001  2022   197313     23604     32875     50085
2      G1-001  2023   349899     51332     71695     89089
3      G1-001  2024   268821     40969     56452     76545
4      G1-001  2025   138115     14516     20889     28968
..        ...   ...      ...       ...       ...       ...
418    P3-027  2025   172191     17127     35088     52215
419    P3-028  2025   220048     15847     45103     91424
420    P3-029  2025   279839     22351     45673     70801
421    P3-030  2025   146829     14505     30602     43338
422    P3-031  2025   275305     19834     41006     60840

[423 rows x 6 columns]

In [27]:
listcol = ["SG-BASED", "COUNTRY OF OVERSEAS CLIENT", "OVERSEAS"]
df.drop(columns=listcol, axis=1, inplace=True)

In [ ]:
df = df.dropna()
df